<a href="https://colab.research.google.com/github/Rijann12/PlantDiseasePrediction/blob/main/ProjectModelTrain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Data Preprocessing

## Training Image Preprocessing

In [ ]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/ProjectData/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(64, 64),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)
# mathi ko directory wala ma hamle save gareko directory ma vako lekhne


Found 58422 files belonging to 32 classes.


In [ ]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 32), dtype=tf.float32, name=None))>

In [ ]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break


tf.Tensor(
[[[[104.5   98.5  100.5 ]
   [102.5   96.5   98.5 ]
   [100.25  94.25  96.25]
   ...
   [100.25  95.25  92.25]
   [ 96.5   91.5   88.5 ]
   [ 92.5   87.5   84.5 ]]

  [[109.   103.   105.  ]
   [ 98.75  92.75  94.75]
   [105.25  99.25 101.25]
   ...
   [ 90.5   85.5   82.5 ]
   [108.   103.   100.  ]
   [ 98.    93.    90.  ]]

  [[103.25  97.25  99.25]
   [ 99.5   93.5   95.5 ]
   [ 92.75  86.75  88.75]
   ...
   [ 98.75  93.75  90.75]
   [ 97.75  92.75  89.75]
   [ 97.5   92.5   89.5 ]]

  ...

  [[148.5  147.5  153.5 ]
   [153.75 152.75 158.75]
   [147.75 146.75 152.75]
   ...
   [123.   118.   125.  ]
   [132.   127.   134.  ]
   [137.25 132.25 139.25]]

  [[145.   144.   150.  ]
   [151.5  150.5  156.5 ]
   [146.   145.   151.  ]
   ...
   [126.   121.   128.  ]
   [127.5  122.5  129.5 ]
   [121.25 116.25 123.25]]

  [[146.25 145.25 151.25]
   [145.5  144.5  150.5 ]
   [144.   143.   149.  ]
   ...
   [131.   126.   133.  ]
   [129.25 124.25 131.25]
   [124.75 119.75 12

## Validation Image Preprocessing


In [ ]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/ProjectData/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 14864 files belonging to 32 classes.


## To avoid Overshooting
1. Choose small learning rate default 0.001 we are taking 0.0001
2. There may be chance of Underfitting, so incresase number of neuron
3. Add more Convolutional layer to extract more feature from images there may  be possibility that the model uanle to captutre relevant feature or model is confusing due to lack of feature so feed with more feature

# Building Model

In [ ]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [ ]:
model = Sequential()

In [ ]:
#Building Convolutional Layer
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))


In [ ]:
model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))


In [ ]:
model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Dropout(0.25))

In [ ]:
model.add(Flatten())

In [ ]:
model.add(Dense(units=1500, activation='relu'))

In [ ]:
model.add(Dropout(0.4))

In [ ]:
# Output layer
model.add(Dense(units=32, activation='softmax'))

#Compiling the model

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy',metrics=['accuracy'] )


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         1,248 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,844,010 (29.92 MB)

 Trainable params: 7,844,010 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

#Model Training

In [ ]:
!nvidia-smi


Sat Jul 12 09:39:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   72C    P0             30W /   70W |     230MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=9
                             )

Epoch 1/9
1826/1826 ━━━━━━━━━━━━━━━━━━━━ 13933s 8s/step - accuracy: 0.0336 - loss: 3.4780 - val_accuracy: 0.0338 - val_loss: 3.4712
Epoch 2/9
1826/1826 ━━━━━━━━━━━━━━━━━━━━ 219s 115ms/step - accuracy: 0.0348 - loss: 3.4677 - val_accuracy: 0.0338 - val_loss: 3.4681
Epoch 3/9
1826/1826 ━━━━━━━━━━━━━━━━━━━━ 205s 112ms/step - accuracy: 0.0349 - loss: 3.4622 - val_accuracy: 0.0338 - val_loss: 3.4675
Epoch 4/9
 487/1826 ━━━━━━━━━━━━━━━━━━━━ 1:58 88ms/step - accuracy: 0.0341 - loss: 3.4596

## Model Evaluation

In [ ]:
# Model Evaluation on Training Set
train_loss, train_acc = model.evaluate(training_set)

In [ ]:
print(train_loss, train_acc)

In [ ]:
# Model validation Set
val_loss, val_acc = model.evaluate(validation_set)

# Saving model

In [ ]:
model.save("trained_model.h5")

In [ ]:
# To save this file we have used 'keras' format as it compresses the file size whereas '.h5' format takes up more file size
model.save("trained_model.keras")


In [ ]:
training_history.history
# validation accuracy tara validation garesi garne
#training_history.history(val_accuracy)

In [ ]:
# Recording the histroy in json
# We have saved this training history in 'json' for future use of the data or perform data visualization as we can just read this history
# Also for the future use of the this model as we cannot run the model again and again if we need it for future
import json
with open("training_hist.json","w") as f:
  json.dump(training_history.history,f);

# Accuracy Visualization

In [ ]:
epochs = { i for in range(1,1)}
epochs

In [ ]:
epochs = { i for in range(1,1)}
plt.plot(epochs, training_history.history ['accuracy'], color= 'red', label='Training Accuracy')
plt.plot(epochs, training_history.history ['val_accuracy'], color= 'blue', label='Vlaidation Accuracy')
plt.xlabel("No. of epochs")
plt.ylabel("Accuracy Result")
plt.title("Visualization Accuracy Result")
plt.legend()
plt.show()

# Some other matrices for model evaluation

In [ ]:
  class_name = validation_set.class_names
  class_name

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/ProjectData/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,# Setting shuffle as False for the testing passes the folders from validation folder sequentially from starting to bottom
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

In [ ]:
y_pred = model.prediction(test_set)
y_pred,y_pred.shape

In [ ]:
predicted_categories = tf.argmax(y_pred,axis=1) # this goes to inside y_pred and extract the maximum value and return the index of that max value and axis=1 means it return the index in column wise

In [ ]:
predicted_categories

In [ ]:
true_categories = tf.concat( [y for x,y in test_set], axis=0)
true_categories

In [ ]:
Y_true=predicted_categories = tf.argmax(y_pred,axis=1)
Y_true

In [ ]:
# Calcualate Precision recall
# Precision measures the precentage made by the model that are correct.
# Recall measures the percenatage of the relevant data points that were correctly identified by the model.


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(classification_report(Y_true, predicted_categories target_names=class_name))

In [ ]:
# F-1 score calculation, perfect model have F-1 score of 1.
cm = confusion_matrix(Y_true, predicted_categories)
cm.shape()

# Visualization of Confusion matrix

In [ ]:
#sns.heatmap(cm)
plt.figure(figsize=(40, 40))
sns.heatmap(cm, annot=True, annot_kws={'size':10})
plt.xlabel("Predicted Class", fontsize=20)
plt.ylabel("Actual Class", fontsize=20)
plt.title("Plant Disease Confusion Matrix", fontsize=20)
plt.show()
# the result is saying it is confusion matix and the diagonal element is saying that it belongs to that class and actually it belings to that class
# we can tune this model by adjusting filters, improving no. of nuerons, adjusting loss function